vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr

    mappings:
        default:
            uri_prefix:         /images/uploads/default
            upload_destination: %kernel.root_dir%/../web/uploads/default
            namer: vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true