xavierlis_user:
    resource: "@XavierlisUserBundle/Resources/config/routing.yml"
    prefix:   /

xl_core:
    resource: "@XavierlisCoreBundle/Resources/config/routing.yml"
    prefix:   /

xl_content:
    resource: "@XavierlisContentBundle/Resources/config/routing.yml"
    prefix:   /
