services:
    xl_admin.menu.listener:
        class: Xavierlis\CoreBundle\Listener\MenuItemListListener
        tags:
            - { name: kernel.event_listener, event: theme.sidebar_setup_menu, method: onSetupMenu }